### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by vKolerts** [RaresAil/gree-ac-node-api#2]
```
const device = await waitForDevice('192.168.1.50');
device.sendCommand('status','');
```

TypeError: device.sendCommand is not a function

Examples please

**Comment by vKolerts** [comment]
More user friendly https://www.npmjs.com/package/gree-hvac-client

**Comment by RaresAil** [comment]
Hello, I am sorry for the late response, if your are using typescript you should have autocomplete, the command is `STATUS` and you don't specify the second parameter for status
